title: 失敗に成功しました
description: 14兆8,000億円 の血税はなぜ消えた？ 支援が沖縄を貧しくする仕組みをゲーム理論で明かす。
theme: just-the-docs

url: https://lisiki-jp.github.io/okinawa_gametheory/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/lisiki-jp/okinawa_gametheory
